export const ADMIN_Route = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LIST_ROUTE = '/registration'
export const RESTAURANT_ROUTE = '/resataurant'
